services:
  - type: web
    name: django-data-inspector
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn datainspector.wsgi --preload --log-file -
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: datainspector.settings
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: SECRET_KEY
        generateValue: true
      - key: DATA_DIR               # donde montaremos el disco
        value: /opt/render/project/src/data
      - key: MEDIA_ROOT
        value: /opt/render/project/src/data/media
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
